<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Quiz;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends EntityRepository {

    public function findQueryForAll() {
        $qb = $this->createQueryBuilder('req');
        $query = $qb->add('select', 'a')->add('from', 'AppBundle:Quiz a')->getQuery();

        return $query;
    }

}
